import pandas as pd 

df = pd.read_excel('wind_power_gen_3months_validation_data.xlsx')

power = df['Power generated by system']

ratio_1 = 0.2
ratio_2 = 0.45
ratio_3 = 0.35

df['c1'] = 0.2 * power
df['c2'] = 0.45 * power
df['c3'] = 0.35 * power

# Merge the columns into a single DataFrame based on the 'DateTime' column
merged_df = pd.merge(df[['DateTime', 'c1']], df[['DateTime', 'c2']], on='DateTime')
merged_df = pd.merge(merged_df, df[['DateTime', 'c3']], on='DateTime')

# Save the merged DataFrame to a CSV file
merged_df.to_csv("c1_c2_c3_2024.csv", index=False)
